vvanholl/elasticsearch-prometheus-exporter

README.md, plugin-descriptor.properties, pom.xml
You have to adjust the release date ;)
=> Elasticsearch 2.4.4 support

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/28)
=> upgrade prometheus libs

plugin-descriptor.properties, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/27)
=> upgrade elasticsearch

README.md, plugin-descriptor.properties, pom.xml
@vvanholl
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/32)
=> support ES 5.4.0

README.md, plugin-descriptor.properties, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/38)
=> support ES 5.4.1

README.md, plugin-descriptor.properties, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/44)
=> Support ES 5.4.2

README.md, gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/45)
=> support ES 5.4.3

build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/49)
=> upgrade prometheus libraries

README.md, gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/48)
=> support ES 5.5.1

build.gradle, src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCatalog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/50)
=> Upgrade prometheus. Avoid lint warning

README.md, gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/55)
@vvanholl
=> Release 5.6.1.0

README.md, gradle.properties
@vvanholl It is time again!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/67)
=> support ES 5.6.4

README.md, gradle.properties
Not verified in any way - let's see if build passes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/69)
=> support es 6

README.md, gradle.properties
@vvanholl  u know the drill
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/73)
=> support ES 6.0.1. Fixes GH #72

build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/77)
=> upgrade prometheus library

README.md, gradle.properties
@vvanholl  U know the drill
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/80)
=> Support ES 6.1.2

README.md, gradle.properties
@vvanholl
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/83)
=> support elastic 6.1.3

README.md, gradle.properties
@vvanholl  U know the drill
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/90)
=> support es 6.2.2

README.md, gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/95)
=> support es 6.2.3

build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/103)
=> upgrade prometheus lib

README.md, gradle.properties
@vvanholl 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/106)
=> release for es 6.3.0

gradle.properties
=> Fix naming

README.md
Readme details has been updated.
=> Readme versions has been fixed.

README.md
=> Remove coverage badge from README

README.md, build.gradle, gradle.properties
To finish the release we need:
- add tag `6.5.3.0` to commit `58b4bfd`
- follow up with usual "Prepare new release" commit
See #148
=> Release version 6.5.3.0

src/test/resources/rest-api-spec/test/resthandler/40_20_cluster_settings_disk_watermark_bytes.yml
=> Cleanup cluster settings in test

build.gradle
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vvanholl/elasticsearch-prometheus-exporter/178)
=> upgrade prometheus libs - fixes #171

README.md, build.gradle, gradle.properties, src/main/java/org/elasticsearch/action/NodePrometheusMetricsAction.java, src/main/java/org/elasticsearch/action/TransportNodePrometheusMetricsAction.java, src/main/java/org/elasticsearch/rest/prometheus/RestPrometheusMetricsAction.java
=> Upgrade to Elasticsearch 7.0.0

README.md, build.gradle, gradle.properties, src/test/resources/rest-api-spec/api/prometheus.metrics.json
=> Upgrade to Elasticsearch 7.2.0

README.md, gradle.properties
Prepare release of 7.2.0.0 related to #198 #199
=> Prepare release

.gitlab-ci.yml, README.md, gradle.properties, src/main/java/org/elasticsearch/action/ClusterStatsData.java, src/main/java/org/elasticsearch/action/NodePrometheusMetricsAction.java, src/main/java/org/elasticsearch/action/NodePrometheusMetricsRequest.java, src/main/java/org/elasticsearch/action/NodePrometheusMetricsResponse.java, src/main/java/org/elasticsearch/action/admin/indices/stats/PackageAccessHelper.java, src/main/java/org/elasticsearch/rest/prometheus/RestPrometheusMetricsAction.java, src/test/resources/rest-api-spec/api/prometheus.metrics.json
=> Upgrade to ES 7.4.0 and release 7.4.0.0

README.md, gradle.properties
=> Upgrade to ES 7.4.1 and release 7.4.1.0

README.md, build.gradle, gradle.properties
- Removing some of the gradle hacks that are no longer needed
- Upgrading Prometheus client library
Closes #238
Closes #246
=> Upgrade to ES 7.5.1 and release 7.5.1.0

README.md, gradle.properties
=> Upgrade to ES 7.5.2 and release 7.5.2.0

.gitlab-ci.yml, README.md, build.gradle, gradle.properties
Hello!
Fixes #272 
I just copied a previous PR #269  - wondering if the integration tests pass without any more changes
=> Upgrade to ES 7.7.1 and release version 7.7.1.0

README.md, gradle.properties
https://www.elastic.co/guide/en/elasticsearch/reference/7.11/release-notes-7.11.2.html
=> Add 7.11.2 to match latest elasticsearch version

README.md, gradle.properties
Updating to latest version of elasticsearch.
=> Update to elasticsearch version 7.13.2

README.md, gradle.properties
Update to elasticsearch version 7.16.0
=> Update to elasticsearch version 7.16.0

README.md, gradle.properties
Update to elasticsearch version 7.16.1
=> Update to elasticsearch version 7.16.1
